新增字符串与数值转换
changkun/modern-cpp-tutorial pull request #123
Opened 2020-09-06 11:15 UTC by changdingfang

## 说明

新增c++11特性, 字符串与数值类型之间的转换

## 变化箱单

- 增加了数值类型转换到字符串类型
- 增加了字符串类型转换到整型(包括int, unsigned int, long int 等等)
- 增加了 字符串类型转换到浮点型(包括float, double等等)
- 增加了简单的转换使用示例

2020-09-09 09:21 UTC, changkun requested changes

2020-09-09 09:21 UTC, changkun commented on book/zh-cn/09-others.md
> +- std::to_string(val)
please add more explanation about the function, also address the importance of having this in the tutorial.

2020-09-09 09:21 UTC, changkun commented on book/zh-cn/09-others.md
> +p是size_t指针, 用来保存s中第一个非数值字符的下标, p默认为0(不保存下标)
these texts are more documentation which does not suit a book. Please considering rephrase it.

2020-09-09 09:21 UTC, changkun commented on book/zh-cn/09-others.md
> +返回s的起始子串(表示浮点数内容)的数值,
same here

2020-09-09 09:21 UTC, changkun commented on book/zh-cn/09-others.md
> +**使用示例**
Please also explain the provided example.

2020-09-11 12:17 UTC, changdingfang commented on book/zh-cn/09-others.md
> +p是size_t指针, 用来保存s中第一个非数值字符的下标, p默认为0(不保存下标)
我理解的是这些说明是有必要的,如果只是写上这些方法,而不进行简单的解释,开发者可能是有些懵的.
这些说明只是让开发者看到该内容后能够基本使用.

2020-10-01 08:17 UTC, changkun commented
抱歉，建议的更改只是对 API 的罗列，并没有包含适合书面写作的用语，不适合合并到书中，关闭。

2020-10-01 08:17 UTC, closed without merging